### ISSUE TITLE
NetLogo 5.3 compatibility?

### ISSUE THREAD

**Issue by SethTisue** [fstonedahl/behaviorsearch#4]
perhaps it works fine, but if you've tried it, it might be comforting to users if the README said so.

**Comment by fstonedahl** [comment]
Good point.  Haven't tried it yet, but will try to check it out pretty soon...

**Comment by SethTisue** [comment]
user report that it doesn't work with 5.3.1: https://groups.google.com/d/msg/netlogo-devel/UMhSnNLj1cY/DYwvl576EAAJ

**Comment by fstonedahl** [comment]
This has been resolved, now that we are bundling it with NetLogo 6 (thanks to some hard work by @mrerrormessage)
